name: Sync Database

on:
  push:
    branches:
      - master
    paths:
      - 'stations/*.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Execute Script
        run: python database.py
      - name: Commit Files
        run: |
          git config --local user.email "${{ vars.GIT_EMAIL }}"
          git config --local user.name "${{ vars.GIT_USER }}"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Sync Database" --allow-empty)
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Mirror files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          state-name: .sync
          exclude: |
            **/.git*
            **/.git*/**
            **/*.py
            **/*.sql
            .github
            lib
            scripts
            .pylintrc
            README.md
            requirements.txt